version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=booktrading
    depends_on:
      mysql:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booktrading
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "go run cmd/migrate/main.go"
    volumes:
      - ./migrations:/app/migrations
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=booktrading
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysql", "-h", "mysql", "-u", "root", "-proot", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: 