basePath: /
definitions:
  book.Book:
    description: Book model for the book trading system
    properties:
      author:
        description: |-
          @Description Author of the book
          @example F. Scott Fitzgerald
        type: string
      created_at:
        description: |-
          @Description When the book was added to the system
          @example 2025-04-28T12:00:00Z
        type: string
      description:
        description: |-
          @Description Description of the book
          @example A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.
        type: string
      id:
        description: |-
          @Description Unique identifier for the book
          @example 1
        type: integer
      photos:
        description: |-
          @Description List of base64 encoded photos of the book
          @example ["data:image/jpeg;base64,/9j/4AAQSkZJRg..."]
        items:
          type: string
        type: array
      state:
        description: |-
          @Description Current state of the book
          @example available
        type: string
      tags:
        description: '@Description List of tags associated with the book'
        items:
          $ref: '#/definitions/tag.Tag'
        type: array
      title:
        description: |-
          @Description Title of the book
          @example The Great Gatsby
        type: string
      updated_at:
        description: |-
          @Description When the book was last updated
          @example 2025-04-28T12:00:00Z
        type: string
    type: object
  book.CreateBookDTO:
    properties:
      author:
        maxLength: 255
        minLength: 1
        type: string
      description:
        maxLength: 1000
        minLength: 1
        type: string
      photos:
        items:
          type: string
        type: array
      state:
        enum:
        - available
        - trading
        - traded
        type: string
      tag_ids:
        items:
          type: integer
        type: array
      title:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - author
    - description
    - state
    - title
    type: object
  book.UpdateBookDTO:
    properties:
      author:
        maxLength: 255
        minLength: 1
        type: string
      description:
        maxLength: 1000
        minLength: 1
        type: string
      photos:
        items:
          type: string
        type: array
      state:
        enum:
        - available
        - trading
        - traded
        type: string
      title:
        maxLength: 255
        minLength: 1
        type: string
    type: object
  tag.CreateTagDTO:
    properties:
      name:
        description: |-
          @Description Name of the tag
          @example fiction
        maxLength: 255
        minLength: 1
        type: string
    required:
    - name
    type: object
  tag.Tag:
    description: Tag model for categorizing books
    properties:
      created_at:
        description: |-
          @Description When the tag was created
          @example 2025-04-28T12:00:00Z
        type: string
      id:
        description: |-
          @Description Unique identifier for the tag
          @example 1
        type: integer
      name:
        description: |-
          @Description Name of the tag
          @example fiction
        type: string
      updated_at:
        description: |-
          @Description When the tag was last updated
          @example 2025-04-28T12:00:00Z
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API for book trading system with tag support
  title: Book Trading API
  version: "1.0"
paths:
  /api/v1/books:
    post:
      consumes:
      - application/json
      description: Create a new book with the given details
      parameters:
      - description: Book details
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/book.CreateBookDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/book.Book'
      summary: Create a new book
      tags:
      - books
  /api/v1/books/{id}:
    get:
      description: Get book information by ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/book.Book'
      summary: Get book by ID
      tags:
      - books
    put:
      consumes:
      - application/json
      description: Update book details
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      - description: Book details
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/book.UpdateBookDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/book.Book'
      summary: Update a book
      tags:
      - books
  /api/v1/books/{id}/tags:
    post:
      consumes:
      - application/json
      description: Add multiple tags to a book
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      - description: Tag IDs
        in: body
        name: tags
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Add tags to book
      tags:
      - books
  /api/v1/books/search:
    get:
      description: Search books that have all specified tags
      parameters:
      - collectionFormat: csv
        description: Tag IDs
        in: query
        items:
          type: integer
        name: tag_id
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/book.Book'
            type: array
      summary: Search books by tags
      tags:
      - books
  /api/v1/tags:
    post:
      consumes:
      - application/json
      description: Create a new tag with the given name
      parameters:
      - description: Tag details
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/tag.CreateTagDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tag.Tag'
      summary: Create a new tag
      tags:
      - tags
  /api/v1/tags/{id}:
    get:
      description: Get tag information by ID
      parameters:
      - description: Tag ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tag.Tag'
      summary: Get tag by ID
      tags:
      - tags
  /api/v1/tags/popular:
    get:
      description: Get list of popular tags
      parameters:
      - description: Number of tags to return
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/tag.Tag'
            type: array
      summary: Get popular tags
      tags:
      - tags
swagger: "2.0"
